### ISSUE TITLE
Mouse velocity/accleration should reset when no movement keys are pressed

### ISSUE THREAD

**Issue by jmdodge** [henrystern/extend_layer#1]
Hi - love the script, thanks for the contribution!

I like having a high top speed for the mouse keys with a moderately slow acceleration ramp-up, however I was finding that it was difficult to control when you wanted to make small adjustments when you're getting close to your target on the screen because small, repeated key taps are still going at max velocity. Although the modifier for smaller velocity works ok, it's a bit awkward to change hand positions to reach it.

I realized that the issue I was having was that when doing many small taps, the acceleration doesn't reset, so instead of getting small movements, you get very large movements - at least until you change the direction of the mouse movement, which is obviously not intuitive.

Anyway, I think the fix is simple and works well for me: just reset the velocity when no movement keys are pressed. This allows me to have a high top speed with an acceleration to ramp up the velocity, but do many short taps for small movements without the speed getting out of control.

I added this to the `MoveCursor` method within class `MouseControls`:
```
        ; Check if no movement keys are pressed
        if (up == 0 and left == 0 and down == 0 and right == 0) {
            this.velocity_x := 0 ; Reset X-axis velocity
            this.velocity_y := 0 ; Reset Y-axis velocity
            return
        }
```

Sorry for not providing a patch/PR.

**Comment by henrystern** [comment]
Thanks, I can't believe I missed that. I've pushed your fix. It results in a lot of redundant assignment but hopefully the interpreter takes care of that.

I'm glad you're liking the script. It didn't get as much attention as my other AHK scripts on the forums but it's definitely the one I find the most useful. 

I've been meaning to rewrite it in v2. I also want to speed up the mark GUI somehow, maybe porting to C++. Just have to find the time.

Thanks again,
Henry
